paddelranking/website/users/forms.py
from flask_babel import _, lazy_gettext as _l
from flask_login import current_user
from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField, FieldList, FormField
from wtforms.fields.html5 import IntegerField, DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField
from wtforms.validators import ValidationError, DataRequired, Email, Length
from flask_wtf.file import FileField, FileAllowed, FileRequired
from sqlalchemy.sql.expression import not_

from paddelranking.website import portraits
from paddelranking.website.models import User, db, Tournament, Player, MatchResultsByTeam, Match

from wtforms_alchemy import ModelForm as SQLModelForm, ModelFormField, model_form_factory, ModelFieldList

BaseModelForm = model_form_factory(FlaskForm)



class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session

class EditProfileForm(FlaskForm):
    """ Edit user personal data """

    email = StringField(_l('Email'), validators=[DataRequired(), Email()])
    name = StringField(_l('Name'), validators=[DataRequired()])
    surname1 = StringField(_l('Surname 1'), validators=[DataRequired()])
    surname2 = StringField(_l('Surname 2'), validators=[])
    portrait = FileField(_l('Portrait'),
        description=_l("Upload an image file up to 16 MB, better if 300x300 (squared)"),
        validators=[
            FileAllowed(portraits, _l('Images only!'))])

    submit = SubmitField(_l('Save'))
    cancel = SubmitField(_l('Cancel'))

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None and user.id != current_user.id:
            raise ValidationError(_l('Please use a different email address.'))


class PlayersForm(ModelForm):
    """ Create a list of players """

    playername = StringField(_l('Player Nick'),
            description=_l("Please, provide a nick lower than 64 characters."),
            validators=[Length(max=64)])

    class Meta:
        # No need for csrf token in this child form
        csrf = False
        model = Player

def possible_players():
    return Player.query.filter_by(createdby=current_user.id)

class BaseTournamentForm(ModelForm):
    class Meta:
        model = Tournament

    submit = SubmitField(_l('Save'))
    cancel = SubmitField(_l('Cancel'))

    name = StringField(_l('Tournament Title'),validators=[DataRequired()])
    point_per_match = IntegerField(_l('Points per match'), validators=[DataRequired()], default=100)
    match_per_round = IntegerField(_l('Matches per round'), validators=[DataRequired()], default=3)
    rounds_qty = IntegerField(_l('Rounds'), validators=[DataRequired()], default=3)
    players = QuerySelectMultipleField(_l('Select the players...'),query_factory=possible_players, get_label='playername')
    players_input = ModelFieldList(FormField(PlayersForm), label=_l("Player"), min_entries=1)
    add_player = SubmitField(_l('Add Player'))


class MatchPointsForm(ModelForm):
    """ Create a list of players """

    set1 = IntegerField(_l('Set 1'))
    set2 = IntegerField(_l('Set 2'))
    set3 = IntegerField(_l('Set 3'))


    class Meta:
        # No need for csrf token in this child form
        csrf = False
        model = MatchResultsByTeam

        all_fields_optional = True
        assign_required = False
        exclude = ['winner', 'score', '_matchpoints', 'gamepoints']
        include_foreign_keys = False



class MatchForm(ModelForm):

    class Meta:
        model = Match
        all_fields_optional = True
        assign_required = False

    matchdate = DateField(_l('Match Date'))
    results = ModelFieldList(FormField(MatchPointsForm), label=_l("Match Score"), min_entries=2, max_entries=2)

    submit = SubmitField(_l('Save'))
    cancel = SubmitField(_l('Cancel'))

paddelranking/website/auth.py
from datetime import datetime
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo

from flask_login import current_user, login_user, logout_user
from .models import User, LoginManager, db



bp = Blueprint('auth', __name__, url_prefix='/auth')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()
    user = User.query.filter_by(username=form.username.data).first()
    if form.validate_on_submit():
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password', 'error')
            return redirect(url_for('auth.login'))

        # login successful
        flash('You have successfully logged in.', 'info')
        login_user(user, remember=form.remember_me.data)

        # update userdata
        user.last_login = datetime.utcnow()
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('users.user', username=user.username))

    return render_template('/auth/login.html', title='Login', form=form)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')


    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if current_user.is_authenticated:
            return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        user.register_date = datetime.utcnow()
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('auth.login'))
    return render_template('/auth/register.html', title='Sing Up', form=form)

paddelranking/website/users/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'users',
    __name__,
    url_prefix='/users',
    template_folder='templates',
    static_folder='static'
)

paddelranking/website/users/routes.py
import os
from datetime import datetime

from flask import (
    flash, g, redirect, render_template, request, url_for, current_app
)
from flask_babel import _
from flask_login import login_required, current_user

from paddelranking.website import portraits
from paddelranking.website.utils import is_current_user, fixtures
from paddelranking.website.models import User, db, Tournament, Player, Match, Round, Team, MatchResultsByTeam
from paddelranking.website.users import blueprint
from paddelranking.website.users.forms import EditProfileForm, BaseTournamentForm, MatchPointsForm, MatchForm


def get_portrait_url():
    """ Gets the path to user's portrait image """
    old_portrait_name = current_user.filename or ''

    filepath = os.path.join(
        os.path.join(
            current_app.config['UPLOADED_PORTRAITS_DEST'],
        ),
        old_portrait_name)

    return filepath

@blueprint.route('/')
@login_required
def users():
    if current_user.is_authenticated:
        return redirect(url_for('users.user', username=current_user.username))
    return redirect(url_for('index'))

@blueprint.route('/<username>/')
@login_required
@is_current_user
def user(username):
    # Evitamos que otro usuario intente acceder a un perfil distinto del suyo

    user = User.query.filter_by(username=username).first_or_404()

    return render_template('users/user.html', user=user, title='My control panel')

@blueprint.route('/<username>/profile.html', methods=('GET', 'POST'))
@login_required
@is_current_user
def edit_profile(username):

    user = User.query.filter_by(id=current_user.id).first()
    form = EditProfileForm(obj=user)
    if form.is_submitted():
        if form.cancel.data:
            flash(_('Changes canceled!'))
            return redirect(url_for('users.user', username=username))

        if form.validate_on_submit():

                form.populate_obj(user)
                user.last_modified = datetime.utcnow()

                if 'portrait' in request.files:
                    # Eliminamos la imagen
                    filepath = get_portrait_url()
                    if os.path.exists(filepath) and user.filename:
                        os.remove(filepath)

                    # Preparamos la nueva imagen
                    portrait = request.files.get('portrait')
                    filename, ext = str(portrait.filename).split('.')
                    portrait.filename = '{}.{}'.format(user.portrait_hash(), ext)
                    filename = portraits.save(portrait)
                    user.filename = filename
                db.session.add(user)
                db.session.commit()
                flash(_('Changes saved!'))

        if form.errors:
            flash(_('Please, correct errors found!'))

    return render_template('/users/edit_profile.html', title=_('Edit my profile'), form=form, filename=user.filename)

@blueprint.route('/<username>/profile/delete', methods=('GET',))
@login_required
def remove_profile_image(username):
    if current_user.username != username:
        flash('You cannot access a control panel other than yours', 'error')
        return redirect(url_for('users.user', username=current_user.username))

    user = User.query.filter_by(id=current_user.id).first()
    filepath = get_portrait_url()
    if os.path.exists(filepath):
        os.remove(filepath)
        user.filename = ''
        db.session.add(user)
        db.session.commit()
        flash('Portrait deleted.')
    return redirect(url_for('users.edit_profile', username=current_user.username))

@blueprint.context_processor
def utility_processor():
    filepath = get_portrait_url()

    if os.path.exists(filepath) and current_user.filename:
        original_image_url = url_for('users.static', filename='uploads/portraits/' + current_user.filename, _external=True)
        url_imagen = current_app.resize(original_image_url, '300x300',fill=1)
    else:
        url_imagen = url_for('static', filename='images/user.png', _external=True)

    return dict(profile_imagen=url_imagen)

@blueprint.route('/<username>/my-tournaments.html')
@login_required
@is_current_user
def my_tournaments(username):

    user = User.query.filter_by(username=username).first_or_404()
    tours = Tournament.query.filter_by(createdby=current_user.id).order_by(Tournament.closed,Tournament.created.desc())
    return render_template('users/my_tournaments.html', user=user, tours=tours, title='My tournaments')

@blueprint.route('/<username>/create-tournament.hmtl', methods=['POST', 'GET'])
@login_required
@is_current_user
def create_tournament(username):

    tour = Tournament()
    form = BaseTournamentForm(request.form)
    form.players.min_entries=4

    if form.add_player.data:
        getattr(form,'players_input').append_entry()
        return render_template('/users/create_tournament.html', title='Create new tournament', form=form)

    if form.is_submitted():
        if form.cancel.data:
            flash(_('Changes canceled!'))
            return redirect(url_for('users.my_tournaments', username=username))

        if form.validate_on_submit():
            newplayers = []
            for newplayer in form.players_input.data:
                if newplayer.get('playername'):
                    player = Player(**newplayer)

                    player.createdby = current_user.id
                    newplayers.append(player)

            form.populate_obj(tour)
            tour.closed = False
            tour.players.extend(newplayers)
            tour.createdby = current_user.id
            db.session.add(tour)
            db.session.commit()
            flash(_('Changes saved!'))
            return redirect(url_for('users.my_tournaments', username=username))

        if form.errors:
            flash('Please, correct errors found!')

    return render_template('/users/create_tournament.html', title=_('Create new tournament'), form=form)

@blueprint.route('/<username>/edit-tour-<int:tourid>.hmtl', methods=['POST', 'GET'])
@login_required
@is_current_user
def edit_tournament(username, tourid):

    user = User.query.filter_by(username=username).first_or_404()
    tour = Tournament.query.filter_by(id=tourid).first_or_404()
    form = BaseTournamentForm(request.form, obj=tour)

    form.players.min_entries=4

    if tour.matches:
        form.point_per_match.render_kw={'readonly': True}
        form.match_per_round.render_kw={'readonly': True}
        form.rounds_qty.render_kw={'readonly': True}
        form.players.render_kw={'readonly': True}
        form.players.data = tour.players.all()

    if form.add_player.data:
        getattr(form,'players_input').append_entry()
        return render_template('/users/edit_tournament.html', title=_('Edit tournament'), form=form)

    if form.is_submitted():
        if form.cancel.data:
            flash(_('Changes canceled!'))
            return redirect(url_for('users.tournament', username=username, id=tourid))

        if form.validate_on_submit():
            newplayers = []
            for newplayer in form.players_input.data:
                if newplayer.get('playername'):
                    player = Player(**newplayer)

                    player.createdby = current_user.id
                    newplayers.append(player)

            delattr(form, 'players_input')
            form.populate_obj(tour)
            tour.players.extend(newplayers)
            tour.createdby = current_user.id
            db.session.add(tour)
            db.session.commit()
            flash(_('Changes saved!'))
            return redirect(url_for('users.tournament', username=username, id=tour.id))

        if form.errors:
            flash(_('Please, correct errors found!'),'error')
    else:
        flash(_('You have already created matches for this tournament. Only few fields can be modified.'), 'error')

    return render_template('/users/edit_tournament.html', title=_('Edit tournament'), form=form, tour=tour, user=user)

@blueprint.route('/<username>/process_add_member', methods=['POST'])
@login_required
@is_current_user
def add_player(username):

    form = BaseTournamentForm()
    getattr(form,'players_input').append_entry()

    return render_template('/users/players.html', form=form)

@blueprint.route('/<username>/tour-<int:id>.hmtl', methods=['POST', 'GET'])
@login_required
@is_current_user
def tournament(username, id):
    user = User.query.filter_by(username=username).first_or_404()
    tour = Tournament.query.filter_by(id=id).first_or_404()

    return render_template('users/tournament.html', user=user, tour=tour)

@blueprint.route('/<username>/tour-<int:tourid>/match-<int:matchid>.hmtl', methods=['POST', 'GET'])
@login_required
@is_current_user
def edit_match(username, tourid, matchid):
    user = User.query.filter_by(username=username).first_or_404()
    tour = Tournament.query.filter_by(id=tourid).first_or_404()
    match = Match.query.filter_by(id=matchid).first_or_404()

    results = match.results
    form = MatchForm(request.form, obj=match, results=results.all())


    if form.is_submitted():
        if form.cancel.data:
            flash(_('Changes canceled!'))
            return redirect(url_for('users.tournament', username=username, id=tour.id))

        if form.validate_on_submit():
            scores = []
            teams = (match.team1, match.team2)

            for idx, score in enumerate(form.results.data):
                # Set score, game points and match points
                gamepoints = 0
                for key, value in score.items(): 
                    gamepoints+= value>=6 and  value*2 or value
                
                score['gamepoints'] = gamepoints
                if not results.all():
                    matchresult = MatchResultsByTeam(**score)
                    matchresult.match_id = match.id
                    matchresult.team = teams[idx]
                else:
                    matchresult = results[idx]
                    for key, value in score.items():

paddelranking/website/users/templates/users/create_tournament.html
{% extends "base_dashboard.html" %}
{% block styles%}
  {{ super() }}
  <link href="{{ url_for('static', filename='build/css/custom.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
	<div class="row right_col" role="main">
    {% block messages %}
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
              {% else %}
              <div class="alert alert-info" role="alert">{{ message }}</div>
              {% endif %}
          {% endfor %}
      {% endif %}
      {% endwith %}
    {% endblock messages %}
    <h1 class="col-md-offset-4">{{title}}</h1>
  	<div>
      <div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
      	<p>{{_('All fields marked with * are required')}}</p>
          
        <script type="text/javascript">

            $("#add-player").on('click', function(event){
                event.preventDefault();
                $.ajax({
                    url: "{{ url_for('users.add_player', username=current_user.username) }}",
                    type : "POST",
                    //dataType : 'json', // data type
                    data : $("#main-form").serialize(),
                    success : function(result) {
                        console.log(result);
                        $("#players").html(result);
                    },
                    error: function(xhr, resp, text) {
                        console.log(xhr, resp, text);
                    }
                });

                event.preventDefault();
                });
        </script>
    

        <form class="form"
          method="POST" 
          action="{{ url_for('users.create_tournament', username=current_user.username) }}" id="main-form">
        {{ form.hidden_tag() }}

          <div class="form-group col-sm-12 col-xs-12">
          {{ form.name.label }} {{ form.name(class="form-control", placeholder=_("Tournament Name")) }}
          </div>
          <div class="form-group col-md-4 col-sm-4 col-xs-12">
          {{ form.point_per_match.label}} {{ form.point_per_match(class="form-control") }}
          </div>
          <div class="form-group col-md-4 col-sm-4 col-xs-12">
          {{ form.match_per_round.label }} {{ form.match_per_round(class="form-control") }}
          </div>
          <div class="form-group col-md-4 col-sm-4 col-xs-12">
          {{ form.rounds_qty.label }} {{ form.rounds_qty(class="form-control") }}
          </div>
          <fieldset class="form-group col-md-8  col-sm-12 col-xs-12" aria-labelledby="players_fieldset">
            <span id="players_fieldset" class="h3">{{_('Players')}}</span>
            
            <div class="form-group">
            {{ form.players.label }} {{ form.players(class="form-control") }}
            </div>
            
            <span id="players">{% include '/users/players.html' %}</span>
            <div class="form-group">
                {{ form.add_player(id="add-player", class="btn btn-success btn-sm") }}
            </div>
          </fieldset>
        <div class="form-group col-md-8 col-sm-12 col-xs-12">{{form.submit(class="btn btn-primary btn-lg")}} {{form.cancel(class="btn  btn-danger btn-lg")}}</div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

paddelranking/website/users/templates/users/edit_match.html
{% extends "base_dashboard.html" %}
{% block styles%}
  {{ super() }}
  <link href="{{ url_for('static', filename='build/css/custom.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
	<div class="row right_col" role="main">
    {% block messages %}
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
              {% else %}
              <div class="alert alert-info" role="alert">{{ message }}</div>
              {% endif %}
          {% endfor %}
      {% endif %}
      {% endwith %}
    {% endblock messages %}
    <h1 class="col-md-offset-4">{{title}}</h1>
  	<div>
      <div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">          
        <form class="form"
          method="POST" 
          action="{{url_for('users.edit_match', username=current_user.username, tourid=tour.id, matchid=match.id)}}" id="main-form">
          {{ form.hidden_tag() }}

          <div class="form-group col-sm-12 col-xs-12">
            {{ form.matchdate.label }} 
            <div class="input-group datepicker1 {% if form.matchdate.errors %}has-error{% endif%}">
              <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
              {{ form.matchdate(class="form-control") }}
            </div>
            {% if form.matchdate.errors %}
              <div class="errors text-danger">{% for error in form.matchdate.errors %}<p>{{ error }}</p>{% endfor %}</div>
            {% endif %}
          </div>

          {% for result in form.results %}    
          <div class="form-row">
            <fieldset class="form-group col-md-12  col-sm-12 col-xs-12 {% if form.results.errors %}has-error{% endif%}">
              <legend class="col-md-12 ">
                  {{ _('Team %(teamid)s:', teamid=loop.index )}}
                  {% if loop.index == 1 %}
                    {% set players = team_players(match.team1) %}
                  {% else %}
                    {% set players = team_players(match.team2) %}
                  {% endif%}
                  {% for player in players %}
                    {% if player  %}
                    <span>
                      {% if players|length > 1 and loop.index > 1%} - {% endif %}{{player.playername}}
                    </span>
                    {% endif%}
                  {% endfor %}
              </legend>
              {% for field in result %}
              <div class="col-md-4 col-sm-4 col-xs-4">{{ field(class="form-control", placeholder=field.label.text, max=7, min=0) }}
                <div class="errors text-danger">
                  {% for error in field.errors %}<p>{{ error }}</p>{% endfor %}
                </div>
              </div>
              {% endfor %}
            </fieldset>
          </div>
          {% endfor %}
        <div class="form-group col-md-8 col-sm-12 col-xs-12">{{form.submit(class="btn btn-primary btn-lg")}} {{form.cancel(class="btn  btn-danger btn-lg")}}</div>
        </form>

      </div>
    </div>
  </div>
{% endblock %}

paddelranking/website/users/templates/users/edit_tournament.html
{% extends "base_dashboard.html" %}
{% block styles%}
  {{ super() }}
  <link href="{{ url_for('static', filename='build/css/custom.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
	<div class="row right_col" role="main">
    {% block messages %}
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
              {% else %}
              <div class="alert alert-info" role="alert">{{ message }}</div>
              {% endif %}
          {% endfor %}
      {% endif %}
      {% endwith %}
    {% endblock messages %}
    <h1 class="col-md-offset-4">{{title}}</h1>
  	<div>
      <div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
      	<p>{{_('All fields marked with * are required')}}</p>
          
        <script type="text/javascript">

            $("#add-player").on('click', function(event){
                event.preventDefault();
                $.ajax({
                    url: "{{ url_for('users.add_player', username=current_user.username) }}",
                    type : "POST",
                    //dataType : 'json', // data type
                    data : $("#main-form").serialize(),
                    success : function(result) {
                        console.log(result);
                        $("#players").html(result);
                    },
                    error: function(xhr, resp, text) {
                        console.log(xhr, resp, text);
                    }
                });

                event.preventDefault();
                });
        </script>
    

        <form class="form"
          method="POST" 
          action="{{ url_for('users.edit_tournament', username=current_user.username, tourid=tour.id) }}" id="main-form">
        {{ form.hidden_tag() }}
          <div class="form-group col-sm-12 col-xs-12">
          {{ form.name.label }} {{ form.name(class="form-control", placeholder=_("Tournament Name")) }}
          </div>
          <div class="form-group col-md-4 col-sm-4 col-xs-12">
          {{ form.point_per_match.label}} {{ form.point_per_match(class="form-control") }}
          </div>
          <div class="form-group col-md-4 col-sm-4 col-xs-12">
          {{ form.match_per_round.label }} {{ form.match_per_round(class="form-control") }}
          </div>
          <div class="form-group col-md-4 col-sm-4 col-xs-12">
          {{ form.rounds_qty.label }} {{ form.rounds_qty(class="form-control") }}
          </div>

          <fieldset class="form-group col-md-8  col-sm-12 col-xs-12" aria-labelledby="players_fieldset">
            <span id="players_fieldset" class="h3">{{_('Players')}}</span>
            
            <div class="form-group">
            {{ form.players.label }} {{ form.players(class="form-control")}}
            </div>
            
            {% if not tour.matches %}
            <span id="players">{% include '/users/players.html' %}</span>
            <div class="form-group">
                {{ form.add_player(id="add-player", class="btn btn-success btn-sm") }}
            </div>
            {% endif %}
          </fieldset>
        <div class="form-group col-md-12 col-sm-12 col-xs-12">
          {{ form.closed.label}} {{ form.closed(class="") }}
        </div>
        <div class="form-group col-md-8 col-sm-12 col-xs-12">{{form.submit(class="btn btn-primary btn-lg")}} {{form.cancel(class="btn  btn-danger btn-lg")}}</div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

paddelranking/website/users/templates/users/players.html
{% if form.players%}
    <div class="form-row">
        <div class="col-1 form-group">{{_('Or add new players here...')}}</div>
    </div>
{% endif %}

{% for player in form.players_input %}    
    <div class="form-row">
        {% for field in player %}
            <div class="col-1 form-group">{{ field(class="form-control", placeholder=_("Player Name")) }}</div>
        {% endfor %}
    </div>
{% endfor %}

paddelranking/website/users/templates/users/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <h1>
      <a href="{{ url_for('users.user', username=current_user.username) }}" class="site_title"><i class="fa fa-spinner"></i> <span>PaddelRanking</span></a>
    </h1>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <a href="{{url_for('users.edit_profile', username=current_user.username)}}" title="Edit my profile">
        <img src="{{ profile_imagen }}" alt="Your photo."  class="img-circle profile_img">
      </a>
    </div>
    <div class="profile_info">
      <span>{{_('Welcome,')}}</span>
      <h2> {{ current_user.name | default(current_user.username, true)}} </h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-home"></i>{{ _('Home') }}<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{{ url_for('users.user', username=current_user.username) }}">{{ _('Back to home') }}</a></li>
            <li><a href="{{url_for('users.edit_profile', username=current_user.username)}}">{{ _('Edit my profile') }}</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-edit"></i>{{ _('Tournaments') }}<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{{url_for('users.create_tournament', username=current_user.username)}}">{{ _('New tournament') }}</a></li>
            <li><a href="{{url_for('users.my_tournaments', username=current_user.username)}}">{{ _('My tournaments') }}</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-bar-chart-o"></i> Stats <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="/data/chartjs">Chart JS</a></li>
            <li><a href="/data/chartjs2">Chart JS2</a></li>
            <li><a href="/data/morisjs">Moris JS</a></li>
            <li><a href="/data/echarts">ECharts</a></li>
            <li><a href="/data/other_charts">Other Charts</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-group"></i>{{_(' Friends ')}}<span class="label label-success pull-right">{{_('Coming Soon')}}</span></a>
          <ul class="nav child_menu">
            <li><a href="/fixed_sidebar">Fixed Sidebar</a></li>
            <li><a href="/fixed_footer">Fixed Footer</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{ url_for('auth.logout') }}">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>